### ISSUE TITLE
On window pc.I am running file transit.php on localhost.It outputs empty.What would be the problem?

### ISSUE THREAD

**Issue by vvsshukla** [chapagain/php-swiss-ephemeris#3]
On windows pc,what are the additional prerequisites to run this repository.On localhost i am getting empty output for transit.php file.
![swissoutput](https://user-images.githubusercontent.com/41117445/42574161-9a273a9a-853b-11e8-8d9d-54392b55137c.png)

**Comment by chapagain** [comment]
One reason might be `exec()` function is disabled in your `php.ini` file.

- Open your `php.ini` file
- Find "**disable_functions=**"
- See if it contains `exec` inside it, for example:
`disable_functions="exec"`
- If `exec` is present in `disable_functions`, then remove `exec` from there.
- Save your `php.ini` file
- Restart apache and see if `transit.php` code works now or not.

**Comment by vvsshukla** [comment]
No.It is showing empty like disable_functions=.

**Comment by chapagain** [comment]
The "sweph/swetest" file is a linux executable ELF format file. Hence, it's not executable on Windows PC.

> **Command**: file sweph/swetest
> **Output**: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.0, not stripped

You can try using docker containers using php, mysql, apache/nginx on a linux OS. You can use this repository to create the necessary docker containers: https://github.com/jcavat/docker-lamp
